id: P006797
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6594
  title: མི་ཆུང་གིས་ནོར་བུ་འཚོལ་བའི་ངོ་མཚར་གཏམ་རྒྱུད།
  author: ''
  volumes:
    8b598852079b42ffb159f7fe197d1b6d:
      image_group_id: I3CN6596
      title: ''
      volume_number: 1
      total_pages: 180
